### ISSUE TITLE
Provide an official attributes hook

### ISSUE THREAD

**Issue by joeldrapper** [joeldrapper/phlex#467]
A few people have expressed an interest in overriding `__attributes__` in order to prepare or validate their tag attributes in some unique way. This is not a supported use-case and was recently broken by #459.

I’m opening this issue to explore the possibility of exposing an official hook like our hooks for `before_template`, `after_template` and `around_template`.

### Performance

Processing a Hash of attributes is by far the slowest thing in Phlex. To manage this, we store a cache of the processed attributes on the first render of any view class. We can then take advantage of this cache in subsequent renders if the attributes are consistent, which is usually the case.

Any hook should ideally happen after the cache check, with any customisations of the attributes included in the cache.

Additionally, adding this hook to Phlex should not slow down normal renders that don't implement the hook.

### Safety

Phlex uses the return value of `__attributes__` in the HTML output, which means if you override `__attributes__` and return a `String` rather than calling and returning `super`, you bypass important HTML-safety checks. Any official attributes hook must not leave the application vulnerable if `super` is not called and returned by the override.

**Comment by joelmoss** [comment]
I have a few uses for this...

1. Be able to side load assets (js, css, etc) whenever specific html classes or other attributes are used. 

2. Add/remove/modify attributes based on other attributes. Kind of like shortcuts

Because these are based on attributes used and will modify the attributes, using the around template hooks won't do the trick really. 

Hope that helps

**Comment by joelmoss** [comment]
Just trying a few things out here, so please be gentle 😁

```ruby
class Phlex::HTML
  def resolve_attributes(**attributes)
    attributes
  end

  private def __fetch_attributes__(**attributes)
    attributes = resolve_attributes(**attributes)
    Phlex::ATTRIBUTE_CACHE[attributes.hash] || __attributes__(**attributes)
  end
end
```

With the above, anywhere you do `Phlex::ATTRIBUTE_CACHE[attributes.hash] || __attributes__(**attributes)`, replace with `__fetch_attributes__(**attributes)`. Then override `resolve_attributes` in your view, making sure to return the attributes.

This works (and fixes #489) , but unfortunately `resolve_attributes` will be called every single time. So would need to find a way of caching that.

The problem I see is the use of `attributes.hash` as the cache key. This should be used after the attributes have been resolved, otherwise it will be incorrect.

So what else could we use for the cache key? A UUID for each element instance?

Thoughts?

**Comment by willcosgrove** [comment]
>The problem I see is the use of attributes.hash as the cache key. This should be used after the attributes have been resolved, otherwise it will be incorrect.

If the goal is to prevent `resolve_attributes` from needing to be called every time, wouldn't you want to base it off the `attributes.hash` _before_ resolving them? The assumption would then have to be that `resolve_attributes` is deterministic, always returning the same output for a given input.

I took a swing at this just for fun. If we changed the arguments to `__attributes__` (and the corresponding final method) to accept a key and the attributes, then we can keep the original attribute's hash key as the cache key.

```ruby
private def __fetch_attributes__(**attributes)
  key = attributes.hash
  Phlex::ATTRIBUTE_CACHE.fetch(key) do
    attributes = resolve_attributes(**attributes) if respond_to?(:resolve_attributes)
    __attributes__(key, **attributes)
  end
end
```

So this will look up based on the provided attributes, and cache the resolved attributes. `__attributes__` is then changed to use that instead of the hash of the provided attributes:

```ruby
private def __attributes__(key, **attributes)
  __final_attributes__(key, **attributes).tap do |buffer|
    Phlex::ATTRIBUTE_CACHE[key] = buffer.freeze
  end
end
```

And the final method just ignores that argument

```ruby
private def __final_attributes__(_key, **attributes)
```

I tried this out on my fork here 1046eddcd90387010c78647556ea5c8e234354e7 and tests are passing, but I haven't done any performance testing on it yet.

Regarding the _need_ for something like this for me, I haven't run into a case where I've needed this functionality. But I can see the potential. I would vote that I value performance over supporting this use case— a vote which is influenced primarily by me not having a need for it 😇 yet?

**Comment by joelmoss** [comment]
My expectation is that the hash should be based on the final attributes used - after resolving the hook. Otherwise it's not "correct". 

I also tried this in my [branch](https://github.com/joelmoss/phlex/tree/resolve_attributes_hook_with_key), but my tests failed...

```ruby
describe 'resolve_attributes hook' do
  describe 'first' do
    view1 = Class.new(Phlex::HTML) do
      def resolve_attributes(**attributes)
        attributes[:class] = '1'
        attributes
      end

      def template
        div(identical: 'attribute') { 'one' }
      end
    end

    view2 = Class.new(Phlex::HTML) do
      def resolve_attributes(**attributes)
        attributes[:class] = '2'
        attributes
      end

      def template
        div(identical: 'attribute') { 'two' }
      end
    end

    it 'renders' do
      expect(view1.new.call).to be == %(<div identical="attribute" class="1">one</div>)
      expect(view2.new.call).to be == %(<div identical="attribute" class="2">two</div>)
    end
  end
end
```

The above test calls two views with a different template, but identical attributes. However, each view implements the `resolve_attributes` hook, and adds a `class` attribute, with each view having a different `class` value.

The last expectation fails for view2, as it uses the resolved attributes from view1. Which it should obviously not do.

I have [another branch](https://github.com/joelmoss/phlex/tree/resolve_attributes_hook) which has a slight variation on my original proposal, which does pass tests.

**Comment by joelmoss** [comment]
FWIW, this is a blocker for me. So i've been having to use my [branch](https://github.com/joelmoss/phlex/tree/resolve_attributes_hook) which has been working nicely, and doesn't suffer to much of a performance hit.

**Comment by willcosgrove** [comment]
>My expectation is that the hash should be based on the final attributes used - after resolving the hook. Otherwise it's not "correct".

You're right, to have it be correct when multiple definitions of `resolve_attributes` are in play, then you either need to cache based on the final attributes which means that you always have to call `resolve_attributes`, or you would have to have a different cache for each definition of `resolve_attributes`.

It seems like the best implementation is going to be dependent on how people expect to use it. It sounds like you have a use case where you would be defining `resolve_attributes` potentially many times across different components, as opposed to one "global" definition of it at an `ApplicationView` level. Your implementation is good for your use case because you only incur the additional performance hit on the components where the method is defined, and nowhere else.

It might be instructive to see an example of some of the `resolve_attributes` definitions you're currently using, and what types of components you're defining them on, if you have the time.

**Comment by joeldrapper** [comment]
Having an attribute cache per view class would solve this. There will be a performance cost. and that's okay, but I’m looking for a way to implement it so that it doesn't hurt performance for people who are not using the feature.

**Comment by joeldrapper** [comment]
@joelmoss I am going to have a proper go at this soon. I’m not promising I’ll find a solution but I will try.

**Comment by joelmoss** [comment]
Shout if you need a hand. Right now I'm having to use my own fork to provide this, so would love to stop doing that 🙏

**Comment by joeldrapper** [comment]
Quick update on this: I found a way to perform optional per-class caching with only a 1% performance overhead on classes that don't opt-in, and about a 10% overhead on classes that do opt-in. 1% is reasonable to me, so I’m happy to proceed with this.

**Comment by joeldrapper** [comment]
@joelmoss sorry this took so long but I’m really happy with the solution we got to in the end.

**Comment by joelmoss** [comment]
Hey no problem bud! Thanks for giving some attention 👏
