### ISSUE TITLE
`onerror` attribute is useful for handling broken `<img>` tags

### ISSUE THREAD

**Issue by hangsu** [joeldrapper/phlex#472]
I'm getting a `Phlex::ArgumentError` when I try to use `onerror` as an attribute.
Looks like it's being disallowed (twice 😆) here:

https://github.com/joeldrapper/phlex/blob/d9842b4869093e734968e64c0ec9a50f91f92d35/lib/phlex/html.rb#L127
https://github.com/joeldrapper/phlex/blob/d9842b4869093e734968e64c0ec9a50f91f92d35/lib/phlex/html.rb#L412-L415

Unfortunately, `onerror` is the only decent way to avoid showing a broken image icon when an `<img>` tag fails to find its `src` (see https://stackoverflow.com/a/22051972/823873)

Was there a reason to be opinionated about allowed html attributes in the first place?

**Comment by joeldrapper** [comment]
The reason this is disallowed — and I don’t know why it’s disallowed twice 😅 — is because it can be used for cross-site scripting attacks. If you were serialising user input from a WYSIWYG editor document AST, for example, it might be possible for a user to create an image tag like this.

```html
<img src="not-real-resource" onerror="alert('evil javascript')">
```

Instead, you could use an event listener in safe external JavaScript.

Alternatively, you can achieve the same result without JavaScript by using an `<object>`. Object tags don't show anything when the resource can't be found, but otherwise they work just as well as `<img>` tags with browser support back to IE8.

```html
<object data="image.jpg" aria-label="alt text"></object>
```

Alternatively, you could show the alternative text or a fallback image by placing it inside the object.

```html
<object data="image.jpg">
  The contents are shown when the resource can’t be found.
</object>
```

**Comment by hangsu** [comment]
> Instead, you could use an event listener in safe external JavaScript.

We've tried this before. Often, the img `src` resolves faster than the external JS

> Alternatively, you can achieve the same result without JavaScript by using an <object>. Object tags don't show anything when the resource can't be found, but otherwise they work just as well as <img> tags with browser support back to IE8.

Our type-checking wants the `data` attribute to be a Hash 😅. I wish they named it `src`..

--

I think we can find a solution though. Thank you for the input.

**Comment by joeldrapper** [comment]
It is funny that they named it data when `data-*` attributes are meant to be open for custom attributes.
