### ISSUE TITLE
Changes to `text`/`plain` method resulting in content output issues

### ISSUE THREAD

**Issue by Bumppoman** [joeldrapper/phlex#518]
This is the same issue occurred in #393.  Previously, the default behavior of `text(object)` would fall back to `object.to_s` (i.e. the `text` would force text output without an explicit `to_s`.). This has changed again in 1.5/1.5.1.

I would again argue that the previous behavior was desired (if you call this method, you are declaring that you want some output if the output is available).  I think an explicit `to_s` is redundant.

**Comment by joeldrapper** [comment]
We removed the implicit `to_s` because a lot of objects respond to `to_s` even when they shouldn't really be expected to output anything. Instances of `Enumerator` return something like this `"#<Enumerator:0x0000000102f5f2c8>"` and an instance of an empty `Array` returns `[]`. That could catch you out if you have a block that iterates over an array, but sometimes it's empty.

```ruby
ul do
  list.each do |item|
    li { item }
  end
end
```

Because the block passed to `ul` doesn't add any `li` tags when empty, `ul` will look at the return value instead. If we call `to_s` on the return value, we'll get `[]`, so the output will be `<ul>[]</ul>`.

If you have specific types of object that you want to format for output, you can define the `format_object` method. When Phlex doesn't know how to format an object, it will pass it to this method expecting it to return a string.

```ruby
def format_object(object)
  case object
  when Money
    object.format
  when Date, DateTime
    object.strftime("%Y-%m-%d")
  else
    super
  end
end
```

You could also return `object.to_s` in this `else` condition if you want that to be the default; otherwise, call `super` from `else` to fall back to Phlex’ default.

**Comment by Bumppoman** [comment]
I agree with the foregoing as to why the element methods don't have an implicit `to_s` but what else would you expect the output of `plain(object)` to be?  It seems that the new behavior (returning either `""` or `nil`) would be less obvious than defaulting to the string value.

**Comment by joeldrapper** [comment]
That’s a good point `plain` could behave differently. If `format_object` returns `nil` for the object, we could try calling `to_s` instead. 🤔
